var TextMap = initTextMap((new URLSearchParams(location.search)).get('lang'));
TextMap.__notFound = {};

function initTextMap(lang) {
    const moreLang = {
        "en": {
            '人数不足以创建话题，请选择至少一个其他用户': 'The number of people is not enough to create a topic, please select at least one other user',
            '请选择至少1个其他用户': 'Please select at least 1 other user',
            '以上是即将删除的内容': 'next delete i18n up data',
            '搜索...': 'Search...',
            '欢迎使用该项目！': 'Welcome use the project!',
            '复制': 'copy',
            '用户名': 'username',
            '密码': 'password',
            '类型': 'type',
            '消息时间': 'message time',
            '更新时间': 'update time',
            '输入消息...': 'Input message ...',
            '发送': 'Send',
            '个人信息': 'My Profile',
            '用户信息': 'User Profile',
            '管理用户信息': 'Manage User Profile',
            '用户ID': 'User ID',
            '用户头像地址': 'User avatar url',
            '用户名': 'Username',
            '用户状态': 'User status',
            '最后更新时间': 'Last update time',
            '是否管理员': 'Is admin',
            '超级管理员': 'Super admin',
            '过期时间': 'Expired time',
            '用户': 'User',
            '登录': 'Login',
            '请输入你的用户名': 'Enter your username',
            '请输入你的密码': 'Enter your password',
            '请再次输入密码': 'Enter your password again',
            '注册': 'Register',
            '退出登录': 'Loginout',
            '你确定要创建一个话题吗？': 'Are you sure you want to create a topic?',
            '创建{num}其他人的话题': 'Create a topic with {num} other users',
            '确定': 'Confirm',
            '取消': 'Cancel',
            '请输入话题名称': 'Enter topic name',
            '话题名称为空': 'Topic name cannot be empty',
            '无效的输入': 'Invalid input',
            '版本': 'version',
            '话题列表': 'Topic List',
            '用户列表': 'User List',
            '删除': 'delete',
            '编辑': 'edit',
            '取消编辑': 'cancel edit',
            '更新': 'update',
            '↻ 刷新': '↻ Reload',
            '⚙ 设置': '⚙ Settings',
            '+ 话题': '+ Topic',
            '- 话题': '- Topic',
            'x 取消': 'x Cancel',
            '设置': 'Settings',
            '清理缓存': 'Clear Cache',
            '创建话题': 'Create Topic',
            '关于': 'About',
            '输入的密码不一致！': 'The two entered passwords are inconsistent!',
            '已注销登录': 'Logged out',
            '登录成功!': 'Login successful!',
            '服务器错误!': 'Server error!',
            '取消未登录时的请求': 'Cancel requests when you are not logged in',
            '未登录': 'Not logged in',
            '响应不是ok状态': 'The response is not ok',
            '请求失败!': 'Request failed!',
            '请求中断': 'Request interrupt',
            '缓存已清除': 'Caches cleared',
            '清除缓存失败': 'Failed to clear caches',
            '请输入旧密码！': 'Please enter old password!',
            '修改资料': 'Update Profile',
            '修改密码': 'Update Password',
            '无效的头像地址': 'Invalid avatar url',
            '请选择至少1个话题': 'Please select at least 1 topic',
            '删除{num}个话题': 'Delete {num} topic',
            '你确定要删除话题吗？': 'Are you sure you want to delete the topics?',
            '话题删除成功!': ' Topic deleted successfully!',
            '话题创建成功!': ' Topic created successfully!',
            '话题更新成功!': ' Topic updated successfully!',
            '删除话题': 'Delete topic',
            '创建话题': 'Create topic',
            '未命中的国际化字段数量': 'The number of missed internationalization fields',
            '👁 左': '👁 Left',
            '👁 右': '👁 Right',
            '消息类型': 'Message Type',
            '加解密的秘钥': 'Encrypt and decrypt the secret key',
            '需要加密的数据': 'Data to encrypt',
            '需要解密的数据': 'Data to decrypt',
            '加密': 'encrypt',
            '解密': 'decrypt',
            '加解密数据': 'Encrypt and decrypt data',
            '刷新': 'refresh',
            '上传文件': 'Upload File',
            '选择文件中...': 'File selecting...',
            '请先选择文件': 'Please select the file first',
            '上传': 'upload',
            '清除': 'clear',
            '上传中...': 'Uploading...',
            '已全部上传': 'All uploaded',
            'xxHash-WASM 初始化完成': 'xxHash-WASM initialization completed',
            '哈希计算功能不可用，请刷新页面': 'The hash calculation function is unavailable. Please refresh the page',
            'xxHash初始化失败': 'The initialization of xxHash failed',
            '无效的消息内容': 'Invalid msg content',
            '正在计算文件哈希...': 'The file xxhash is being calculated...',
            '关闭预览': 'close preview',
            '预览': 'preview',
            '总人数': 'users total',
            '加载Python代码运行环境失败': 'Failed to load the Python code runtime environment',
            '正在加载python模块': 'The python packages is being loaded',
            '没有导包或解析失败': 'There was no packages import or parsing failure',
            '正在加载Python代码运行环境中': 'Python code is being loaded in the runtime environment',
            '请稍等': 'Please waiting',
            'Python代码运行环境加载成功': 'The Python code runtime environment was loaded successfully',
            '打断信息': 'Interrupt message',
            '全屏': 'Fullscreen',
            '保存数据': 'Save database',
            '普通输入框无法开启全屏模式': 'The normal input box cannot enable full-screen mode',
            '切换输入框': 'Switch input box',
            '↓ 注销': '↓ Logout',
            '@ 全部用户': '@ All Users',
            '@ 全部话题': '@ All Topics',
            '选择日期和时间': 'Select date and time',
            '旧密码': 'Old password',
            '新密码': 'New password',
            '再次输入新密码': 'New password again',
            '你确定要注销这些用户的登录状态吗？': 'Are you sure you want to log off the login status of these users?',
            '注销{num}人的登录状态': 'Logout of {num} person',
            '话题ID': 'topicID',
            '话题标题': 'topic name',
            '人员总数': 'user total',
            '管理员总数': 'admin total',
            '广场模式': 'public mode',
            '修改话题': 'update topic',
            '删除话题': 'delete topic',
            '退出话题': 'exit topic',
            '用户拉人加入': 'Users are inviting user to join',
            '无法删除他人的话题': "It's impossible to delete others' topic",
            '你确定要删除话题 {name} 吗？': 'Are you sure you want to delete the topic {name}?',
            '你确定要退出话题 {name} 吗？': 'Are you sure you want to exit the topic {name}?',
        }
    };
    return moreLang[lang] || { __empty: true }
}

function i18n(txt, firstToUpperCase = false) {
    let re = TextMap[txt] || txt;
    if (!TextMap.__empty && typeof TextMap[txt] != 'string') {
        if (TextMap.__notFound[txt]) {
            TextMap.__notFound[txt]++;
        } else {
            TextMap.__notFound[txt] = 1;
        }
    }
    return firstToUpperCase ? re.charAt(0).toUpperCase() + re.slice(1) : re;
}