services:
  app:
    build: .
    container_name: LazierServer
    restart: unless-stopped
    ports:
      - "3344:3344"
      - "3345:3345"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - ./ld/logs:/app/ld/logs
      - .:/ls